### ISSUE TITLE
Please add @RequestScoped for OnlyCXF project to reproduce an issue

### ISSUE THREAD

**Issue by dmaidaniuk** [Daniel-Dos/InjectParamsTest-Ozark-CXF#1]
It is enough to add annotation `javax.enterprise.context.RequestScoped` into class [InjectParams](https://github.com/Daniel-Dos/InjectParamsTest-Ozark-CXF/blob/master/OnlyCXF/src/main/java/only/cxf/app/InjectParams.java) from OnlyCXF application and also add `beans.xml` to the resources folder. This will generate `$OwbNormalScopeProxy` instance instead of `$OwbInterceptProxy`. However, the current [issue](https://github.com/mvc-spec/ozark/issues/168) from Ozark project reproduces for this proxy too.

**Comment by Daniel-Dos** [comment]
Hi @dmaidaniuk ,

Sorry for the delay, I just saw github's email today.
I made the update with the change that you reported.

thank you so much.

**Comment by dmaidaniuk** [comment]
Hi @Daniel-Dos ,

Thanks. This sample application could be used for reproducing an issue [CXF-7834](https://issues.apache.org/jira/browse/CXF-7834). Could you attach a link to your repository in mentioned CXF issue?
I'm going to close this issue.

Regards,
Dmytro

**Comment by Daniel-Dos** [comment]
Hello @dmaidaniuk 

I'll include the link no issues created.

thank you.

**Comment by Daniel-Dos** [comment]
made the inclusion of the link to this repository.

thank you.

**Comment by dmaidaniuk** [comment]
Great! Thanks.
