### ISSUE TITLE
Ambiguous URLs for REST end-points

### ISSUE THREAD

**Issue by dmaidaniuk** [Daniel-Dos/InjectParamsTest-Ozark-CXF#2]
I noticed that sample application has ambiguous URLs for 2 GET-methods in controller [InjectParams](https://github.com/Daniel-Dos/InjectParamsTest-Ozark-CXF/blob/master/OnlyCXF/src/main/java/only/cxf/app/InjectParams.java). Both methods `getFieldParam()` and `getFieldParam2(...)` pointed to the same URL `app/hello`:
```
WARNING [http-nio-8080-exec-16] org.apache.cxf.jaxrs.model.OperationResourceInfoComparator.compare Both only.cxf.app.InjectParams#getFieldParam2 and only.cxf.app.InjectParams#getFieldParam are equal candidates for handling the current request which can lead to unpredictable results
```
It is better to change URL for `getFieldParam2(...)` to something like `@Path("/param")` to avoid collision.

Regards,
Dmytro

**Comment by Daniel-Dos** [comment]
Hello @dmaidaniuk 

I made the update including @path in both methods.

thanks again .

**Comment by dmaidaniuk** [comment]
@Daniel-Dos, thanks!
Issue closed.

**Comment by Daniel-Dos** [comment]
your welcome
